### PR TITLE
chore: add `docker` to `dependabot` config

### PR DESCRIPTION
**Pull request by vil02**
I have notice that some of the dockerfiles are slightly out of date. This PR updates the dependabot configuration, to keep them updated.

### CODE REVIEW

**Review by abdfnx — APPROVED** [review]
thanks @vil02

**Comment by vil02** [comment]
@abdfnx do you have some idea why `dependabot` does not update this:
https://github.com/abdfnx/botway/blob/eb6a6a095fc2247084a4ef1dc5106c6181301f7b/docker/gp-image.dockerfile#L1

It seems to be out of date - the newest available is [`gitpod/workspace-base/2023-11-02-17-35-17`](https://hub.docker.com/layers/gitpod/workspace-base/2023-11-02-17-35-17/images/sha256-2cd332405e3b43c0636ccdf8e34d8bb20815c01af966d8667dffea8a81a71413?context=explore).

**Comment by abdfnx** [comment]
> @abdfnx do you have some idea why `dependabot` does not update this:
> https://github.com/abdfnx/botway/blob/eb6a6a095fc2247084a4ef1dc5106c6181301f7b/docker/gp-image.dockerfile#L1
> 
> It seems to be out of date - the newest available is [`gitpod/workspace-base/2023-11-02-17-35-17`](https://hub.docker.com/layers/gitpod/workspace-base/2023-11-02-17-35-17/images/sha256-2cd332405e3b43c0636ccdf8e34d8bb20815c01af966d8667dffea8a81a71413?context=explore).

Yep, it's very weird, I'll find a solution, thanks for your comment

**Comment by vil02** [comment]
> > @abdfnx do you have some idea why `dependabot` does not update this:
> > https://github.com/abdfnx/botway/blob/eb6a6a095fc2247084a4ef1dc5106c6181301f7b/docker/gp-image.dockerfile#L1
> > 
> > It seems to be out of date - the newest available is [`gitpod/workspace-base/2023-11-02-17-35-17`](https://hub.docker.com/layers/gitpod/workspace-base/2023-11-02-17-35-17/images/sha256-2cd332405e3b43c0636ccdf8e34d8bb20815c01af966d8667dffea8a81a71413?context=explore).
> 
> Yep, it's very weird, I'll find a solution, thanks for your comment

As far as I read, the line `directory: "/"` does not make the `dependabot` to scan all of the directories _recursively_ (with an exception of `/.github/workflows` in case of `package-ecosystem: "github-actions"`). I have found this: 
https://github.com/dependabot/dependabot-core/issues/2824#issuecomment-741693711

Should I update the `dependabot` config, to have `"docker"` entry for every directory containing dockerfiles?

**Comment by abdfnx** [comment]
No problem man

**Pull request merged**
